# Generated by Django 3.1.6 on 2021-05-17 07:49

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mamik', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('age', models.IntegerField(default=-1)),
                ('salary', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=3)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('img_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.image_directory_path)),
                ('is_pfp', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
