# Generated by Django 3.1.6 on 2021-06-02 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100)),
                ('email', models.CharField(default='None', max_length=100)),
                ('phone', models.CharField(default='None', max_length=100)),
                ('is_mamik', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('age', models.IntegerField(default=-1)),
                ('salary', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=3)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('img_num', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seeker'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
