# Generated by Django 3.1.6 on 2021-06-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210602_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='phone',
        ),
        migrations.AddField(
            model_name='seeker',
            name='first_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='second_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
