# Generated by Django 3.1.6 on 2021-06-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210602_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='country',
            field=models.CharField(default='None', max_length=3),
        ),
    ]
