# Generated by Django 3.1.6 on 2021-06-02 21:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210602_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=main.models.image_directory_path),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
