# Generated by Django 3.1.6 on 2021-06-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_seeker_img_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='email',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
