# Generated by Django 3.1.6 on 2021-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_seeker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='country',
            field=models.CharField(default='None', max_length=4),
        ),
    ]
