# Generated by Django 3.1.6 on 2021-06-02 22:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_seeker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='profile_pic',
            field=models.ImageField(default='olikpipi.png', upload_to=main.models.image_directory_path),
        ),
    ]
