# Generated by Django 3.1.6 on 2021-06-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210602_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
